apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: helloapurv
  name: helloapurv
spec:
  containers:
  - command: ["/bin/sh", "-c", "ping -i 10 www.google.com > /tmp/adhoc.txt"]
    image: alpine
    name: helloapurv
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
