apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: hello2apurv
  name: hello2apurv
spec:
  containers:
  - command: ["/bin/sh", "-c", " ping google.com"]
    image: alpine
    name: hello2apurv
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
